In [140]:
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

In [141]:
movie_review = pd.read_csv(r"C:\Users\rajukk\Downloads\Movie_review.csv")

In [142]:
df = pd.DataFrame(movie_review)
df.head()

,productId,userId,profileName,helpfulness,review_score,review_time,review_summary,text
0,B002OHDRF2,A2ATWKOFJXRRR1,B. Merritt filmreviewstew.com,2/6,2.0,1263859200,Been There. Done That.,Judgment Day</a> in which a Termina...
1,B002OHDRF2,A1W6I2VUOWRE56,Mohammad Saadat hashem,2/6,5.0,1256256000,leave it alone!!,this is a great movie of course i...
2,B002OHDRF2,A2Y2L2TRP2Q4AS,Jennifer L Kehs,4/10,5.0,1249344000,best Terminator movie!,D Saw the film 4 times in the th...
3,B002OHDRF2,AGC3LQMMYX1RY,Joseph M. Day JOJO77,4/10,5.0,1243555200,this is an awsome movie to see. a...,this movie is the best ever seen. ...
4,B002OHDRF2,A12Q0LLN5R2XAG,MONTY,0/3,5.0,1276646400,TERMINATOR SALVATION,product was in excellent condition. ...

Punkt Sentence Tokenizer. This tokenizer divides a text into a list of sentences, by using an unsupervised algorithm to build a model for abbreviation words, collocations, and words that start sentences. It must be trained on a large collection of plaintext in the target language before it can be used.

In [143]:
#import nltk
#nltk.download('punkt')  #this is used to download punkt

In [144]:
from nltk import word_tokenize,sent_tokenize

In [145]:
df["tokenized_text"] = df["text"].apply(word_tokenize)
#df["tokenized_text"]

In [146]:
df.head()

,productId,userId,profileName,helpfulness,review_score,review_time,review_summary,text,tokenized_text
0,B002OHDRF2,A2ATWKOFJXRRR1,B. Merritt filmreviewstew.com,2/6,2.0,1263859200,Been There. Done That.,Judgment Day</a> in which a Termina...,"[Judgment, Day, <, /a, >, in, which, a, Termin..."
1,B002OHDRF2,A1W6I2VUOWRE56,Mohammad Saadat hashem,2/6,5.0,1256256000,leave it alone!!,this is a great movie of course i...,"[this, is, a, great, movie, of, course, it, is..."
2,B002OHDRF2,A2Y2L2TRP2Q4AS,Jennifer L Kehs,4/10,5.0,1249344000,best Terminator movie!,D Saw the film 4 times in the th...,"[D, Saw, the, film, 4, times, in, the, theater..."
3,B002OHDRF2,AGC3LQMMYX1RY,Joseph M. Day JOJO77,4/10,5.0,1243555200,this is an awsome movie to see. a...,this movie is the best ever seen. ...,"[this, movie, is, the, best, ever, seen, ., we..."
4,B002OHDRF2,A12Q0LLN5R2XAG,MONTY,0/3,5.0,1276646400,TERMINATOR SALVATION,product was in excellent condition. ...,"[product, was, in, excellent, condition, ., sh..."

Lets remove stop which we don't require

In [147]:
stop =['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't"]

In [148]:
def rmstopwords(y):
  A = []
  for i in y:
    if i not in stop:
      A.append(i)   
  return A

In [149]:
lista=df['tokenized_text']
listb=[]
for item in lista:
    b = rmstopwords(item)
    listb.append(b)   
df['text_without_keywords']=listb
#df['text_without_keywords'].head()

In [150]:
df.head()

,productId,userId,profileName,helpfulness,review_score,review_time,review_summary,text,tokenized_text,text_without_keywords
0,B002OHDRF2,A2ATWKOFJXRRR1,B. Merritt filmreviewstew.com,2/6,2.0,1263859200,Been There. Done That.,Judgment Day</a> in which a Termina...,"[Judgment, Day, <, /a, >, in, which, a, Termin...","[Judgment, Day, <, /a, >, Terminator, gets, fr..."
1,B002OHDRF2,A1W6I2VUOWRE56,Mohammad Saadat hashem,2/6,5.0,1256256000,leave it alone!!,this is a great movie of course i...,"[this, is, a, great, movie, of, course, it, is...","[great, movie, course, james, cameron, movie, ..."
2,B002OHDRF2,A2Y2L2TRP2Q4AS,Jennifer L Kehs,4/10,5.0,1249344000,best Terminator movie!,D Saw the film 4 times in the th...,"[D, Saw, the, film, 4, times, in, the, theater...","[D, Saw, film, 4, times, theater, !, !]"
3,B002OHDRF2,AGC3LQMMYX1RY,Joseph M. Day JOJO77,4/10,5.0,1243555200,this is an awsome movie to see. a...,this movie is the best ever seen. ...,"[this, movie, is, the, best, ever, seen, ., we...","[movie, best, ever, seen, ., waiting, long, ti..."
4,B002OHDRF2,A12Q0LLN5R2XAG,MONTY,0/3,5.0,1276646400,TERMINATOR SALVATION,product was in excellent condition. ...,"[product, was, in, excellent, condition, ., sh...","[product, excellent, condition, ., shop, confi..."

In orde to calicualte the sentiment score. AFINN is a list of words rated for valence with an integer between minus five (negative) and plus five (positive).

In [151]:
afinn = pd.read_csv(r"C:\Users\rajukk\Downloads\Afinn.csv",encoding = "ISO-8859-1")
df_afinn = pd.DataFrame(afinn)
df_afinn.head()

        Word  Score
0    abandon     -2
1  abandoned     -2
2   abandons     -2
3   abducted     -2
4  abduction     -2

Converting into dictionary for comparison

In [152]:
afinn_dict = dict(zip(df_affin.Word,df_affin.Score))
#afinn_dict

In [153]:
def sentiment_score(array):
  A = []
  for i in array:
    if i in afinn_dict:
      A.append(afinn_dict[i])
    else:
      A.append(0)
  return A

In [154]:
lista = df["text_without_keywords"]
listb = []
listc = []
#print(lista)
for arrays in lista:
    listb = sentiment_score(arrays)
    listc.append(np.sum(listb))
df["sentiment_scores"] = listc

In [155]:
df["sentiment_scores"].head()

0     4
1    10
2     0
3     3
4     3
Name: sentiment_scores, dtype: int64

In [156]:
df["sentiment_scores"].describe()

count    201.000000
mean       6.373134
std       10.987041
min      -13.000000
25%        0.000000
50%        4.000000
75%       10.000000
max       74.000000
Name: sentiment_scores, dtype: float64